server:
  port: 29007
spring:
  profiles:
    include: datasource,redis,sequence
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
  application:
    name: payment

mybatis-plus:
  global-config:
    db-config:
      logic-delete-field: deleted  # 逻辑删除字段名
      logic-delete-value: true
      logic-not-delete-value: false
      id-type: auto
  mapper-locations: classpath:mapper/**/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true
